# The `service` block is the name of the service
service: badipchecker

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  stage: production
  timeout: 10
  environment:
    UploadBucket: 'badipchecker'
  apiGateway:
    shouldStartNameWithService: true
  lambdaHashingVersion: '20201221'
  iamRoleStatements:
    - Effect: "Allow"
      Action:
       - dynamodb:Query
       - dynamodb:Scan
       - dynamodb:GetItem
       - dynamodb:PutItem
       - dynamodb:UpdateItem
       - dynamodb:DeleteItem
       - dynamodb:DescribeTable
      Resource: "arn:aws:dynamodb:#{AWS::Region}:#{AWS::AccountId}:table/badips"

functions:
  badipchecker:
    handler: badipchecker.handler
    events:
      - http:
          path: badipchecker
          method: post
          cors: true
  updatebadip:
    handler: updatebadip.handler
    events:
      - schedule: rate(24 hours)

resources: # CloudFormation template syntax from here on.
  Resources:
    badips:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: badips
        KeySchema:
          - AttributeName: ipaddress
            KeyType: HASH
        AttributeDefinitions:
          - AttributeName: ipaddress
            AttributeType: S
        BillingMode: PAY_PER_REQUEST

plugins:
  - serverless-pseudo-parameters
